In [1]:
import numpy as np
np.set_printoptions(suppress=True, precision=4)
A = np.array([[4., 1.], [2., 3.]])
b = np.array([9., 13.])
v = np.array([3., -4.])

In [2]:
# @ vs * 
print(A @ A)    # [[18, 7], [14, 11]]
print(A * A)    # [[16, 1], [ 4,  9]]

[[18.  7.]
 [14. 11.]]
[[16.  1.]
 [ 4.  9.]]


In [3]:
#inverse
print(np.linalg.inv(A))

#Determinent
print(np.linalg.det(A))

[[ 0.3 -0.1]
 [-0.2  0.4]]
10.000000000000002


In [4]:
#Ax=b solve func

x=np.linalg.solve(A,b)
print(x,A @ x)

[1.4 3.4] [ 9. 13.]


In [5]:
#cond:how nasty is a matrix 
#Condition number = (largest singular value)/(smallest singular value). It measures how much errors get amplified.
print(np.linalg.cond(A))     # 2.618  → healthy

2.6180339887498945


In [6]:
np.linalg.inv(np.array([[1., 2.], [2., 4.]]))   # LinAlgError: Singular matrix

LinAlgError: Singular matrix

In [11]:
#norms
print(np.linalg.norm(A))
print(np.linalg.norm(A,ord=1))
print(np.linalg.norm(v,ord=1))
print(np.linalg.norm(v, np.inf))

5.477225575051661
6.0
7.0
4.0


In [14]:
#matrix_rank: Rank = number of truly independent columns.
print(np.linalg.matrix_rank(A) )                             # 2  (full rank)
print(np.linalg.matrix_rank(np.array([[1.,2.],[2.,4.]])) )   # 1  (column 2 = 2 × column 1)

2
1


In [15]:
#eigenval & eigenvector
vals, vecs = np.linalg.eig(A)
print(vals)      # [5.+0.j  2.+0.j]
print(vecs)      # columns: [0.7071, 0.7071] and [-0.4472, 0.8944]
print(A @ vecs[:, 0], vals[0] * vecs[:, 0])      # both [3.5355, 3.5355] ✅The eigenvectors are the COLUMNS (vecs[:, 0]), not the rows. This is a very common mistake.

[5. 2.]
[[ 0.7071 -0.4472]
 [ 0.7071  0.8944]]
[3.5355 3.5355] [3.5355 3.5355]


In [17]:
S = np.array([[2., 1.], [1., 2.]])
vals, vecs = np.linalg.eigh(S) # vals = [1., 3.]  (ascending!)
print(vals)
print(vecs)

[1. 3.]
[[-0.7071  0.7071]
 [ 0.7071  0.7071]]


In [18]:
#SVD : singlular value decomposition

U, s, Vt = np.linalg.svd(A)
print(s)                        # [5.1167 1.9544]   singular values, largest first
print(U @ np.diag(s) @ Vt)      # [[4. 1.] [2. 3.]]  rebuilds A ✅

[5.1167 1.9544]
[[4. 1.]
 [2. 3.]]
