In [32]:
#random  api:Creates a Generator object, your personal random-number machine. The seed (42) fixes its starting point
import numpy as np
rng = np.random.default_rng(42)
print(type(rng))
print(rng.random(2))
print(rng.random(2))
print(rng.random(2))

<class 'numpy.random._generator.Generator'>
[0.77395605 0.43887844]
[0.85859792 0.69736803]
[0.09417735 0.97562235]
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [33]:
#sampling method

import numpy as np
rng = np.random.default_rng(42)
#Uniform floats in [0, 1), i.e. 0 can appear, 1 can't
rng.random(5)            # [0.774 0.439 0.859 0.697 0.094]
rng.random((2, 3))       # [[0.976 0.761 0.786]
                         #  [0.128 0.450 0.371]]
#Random integers
rng.integers(1, 7, size=10)   # [2 6 5 4 3 5 4 3 3 2]
#Draws from an array of options
rng.choice(["card", "online", "atm"], size=6, p=[0.5, 0.4, 0.1])
                         # ['online' 'card' 'online' 'online' 'online' 'card']

array(['online', 'card', 'online', 'online', 'online', 'card'],
      dtype='<U6')

In [34]:
#Use permutation when you want a result, shuffle when you want to modify
import numpy as np
x = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
print(x)
rng.permutation(x)         # [3 2 6 5 1 4 8 0 7 9]   a shuffled COPY
print(x)                   # [0 1 2 3 4 5 6 7 8 9]   unchanged
rng.shuffle(x)             # returns None
print(x)                   # [0 5 8 1 2 7 9 6 4 3]   x itself was changed

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 5 8 1 2 7 9 6 4 3]


In [35]:
#Simulating every distribution

rng = np.random.default_rng(42)
N = 100_000          # underscores are just visual separators: 100000

bern  = rng.binomial(n=1, p=0.01, size=N) #n trials, success prob p. No separate Bernoulli function: use n=1
binom = rng.binomial(n=20, p=0.1, size=N) 
geom  = rng.geometric(p=0.1, size=N) #Counts trials until first success, so the minimum is 1 (our geom.min() printed 1)
pois  = rng.poisson(lam=3, size=N) #lam = λ (written lam because lambda is a reserved word in Python)
unif  = rng.uniform(low=0, high=10, size=N) #Continuous on [low, high)
norm  = rng.normal(loc=65, scale=10, size=N) #loc = mean μ, scale = SD σ, not variance. normal(65, 100) would be a huge mistake
expo  = rng.exponential(scale=20, size=N) #scale = mean = 1/λ, not λ. Rate 3 per hour → scale=1/3
logn  = rng.lognormal(mean=np.log(30), sigma=1, size=N) #mean and sigma are of log(X), not X. Median £30 → mean=np.log(30)
par   = 1 * (1 + rng.pareto(a=3, size=N)) #a = α. Returns the shifted "Lomax" form starting at 0, so add 1 and multiply by x_m



In [36]:
print(bern[:20], bern.dtype, bern.shape)
# [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] int64 (100000,)
print(pois[:10])          # [4 0 0 6 1 4 3 1 4 2]
print(np.median(logn))    # 30.07   ← the median we designed

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] int64 (100000,)
[4 0 0 6 1 4 3 1 4 2]
30.06696791338014


In [18]:
#comparing sample statistics with theory
theory = {
    "Bernoulli(0.01)": (bern, 0.01, 0.01 * 0.99),
    "Binomial(20,0.1)": (binom, 20 * 0.1, 20 * 0.1 * 0.9),
    # ... one entry per distribution: (samples, theoretical mean, theoretical variance)
}
for name, (s, m, v) in theory.items():
    sv = s.var(ddof=1)
    print(f"{name:22s}{s.mean():9.3f}{m:9.3f}{sv:11.3f}{v:11.3f}{100*abs(sv-v)/v:7.1f}")

Bernoulli(0.01)           0.010    0.010      0.010      0.010    1.4
Binomial(20,0.1)          1.999    2.000      1.803      1.800    0.1


In [37]:
np.any(risky), np.all(amount > 0)   # True, True
np.flatnonzero(risky)               # [1 4 7]   positions of the Trues
X[X[:, 0] > 100]                    # filter ROWS of the 2-D matrix
np.isin(hour, [2, 3, 23])           # membership test

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [29]:
capped = amount.copy()
capped[capped > 500] = 500
# [ 12.5 230. 45. 8.99 500. 60. 15. 410. 33. 75. ]

In [30]:
z = np.array([1.0, np.nan, 3.0])
np.isnan(z)              # [False  True False]
z[~np.isnan(z)].mean()   # 2.0   drop NaNs, then average
np.nanmean(z)            # 2.0   NaN-aware version (also np.nansum, np.nanstd, np.nanmedian…)

np.float64(2.0)

In [31]:
a = np.arange(10)
v = a[2:5]               # slice → VIEW
v[0] = 99
print(a)                 # [ 0  1 99  3  4  5  6  7  8  9]   original changed!
np.shares_memory(a, v)   # True
v.base is a              # True

a = np.arange(10)
c = a[[2, 3, 4]]         # fancy → COPY
c[0] = 99
print(a)                 # [0 1 2 3 4 5 6 7 8 9]   unchanged
np.shares_memory(a, c)   # False

a = np.arange(10)
b = a[a > 5]             # boolean → COPY
b[:] = 0
print(a)                 # unchanged

[ 0  1 99  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [39]:
#part c axis aggregations np.where,np.select
spend = np.array([
    [20, 35,   0, 15, 30],   # customer 0: regular
    [ 0,  0, 500,  0,  0],   # customer 1: one huge spend, nothing else
    [12, 10,  14, 11, 13],   # customer 2: small and steady
    [60, 45,  80, 55, 70],   # customer 3: big and steady
], dtype=float)
print(spend.shape, spend.ndim, spend.size)   # (4, 5) 2 20

spend.sum(), spend.mean(), spend.min(), spend.max()   # 970.0  48.5  0.0  500.0
np.median(spend)                                      # 14.5
np.percentile(spend, [25, 75])                        # [ 7.5 47.5]   Q1 and Q3


(4, 5) 2 20


array([ 7.5, 47.5])

In [43]:
''' 
axis=0 collapses the rows. You move down each column, so you get one value per column (per day).
axis=1 collapses the columns. You move across each row, so you get one value per row (per customer).
'''
print(spend.sum(axis=0))     # [ 92.  90. 594.  81. 113.]   shape (5,)
print(spend.mean(axis=0))    # [ 23.  22.5 148.5 20.25 28.25]


spend.sum(axis=1)                  # [100. 500.  60. 310.]   shape (4,)
spend.mean(axis=1)                 # [ 20. 100.  12.  62.]
spend.std(axis=1, ddof=1)          # [ 13.69 223.61  1.58  13.51]
np.median(spend, axis=1)           # [20.  0. 12. 60.]
np.percentile(spend, 50, axis=1)   # [20.  0. 12. 60.]   same as median


#argmax:argmin : position of max and min
print(spend.max(axis=1))      # [ 35. 500.  14.  80.]
print(spend.argmax(axis=1))   # [1 2 2 2]   which day each customer spent the most

[ 92.  90. 594.  81. 113.]
[ 23.    22.5  148.5   20.25  28.25]
[ 35. 500.  14.  80.]
[1 2 2 2]


In [44]:
#keepdims=True keeps the collapsed dimension as size 1, so the result lines up:
tot_k = spend.sum(axis=1, keepdims=True)   # shape (4, 1)
share = spend / tot_k
# [[0.2  0.35 0.   0.15 0.3 ]
#  [0.   0.   1.   0.   0.  ]
#  [0.2  0.17 0.23 0.18 0.22]
#  [0.19 0.15 0.26 0.18 0.23]]
share.sum(axis=1)                          # [1. 1. 1. 1.]  ✔

array([1., 1., 1., 1.])

In [45]:
#np.where(condition, value_if_true, value_if_false)

high = np.where(amount > 100, 1, 0)
# [0 1 0 0 1 0 0 1 0 0]
label = np.where(amount > 100, "high", "low")
# ['low' 'high' 'low' 'low' 'high' 'low' 'low' 'high' 'low' 'low']
capped = np.where(amount > 500, 500, amount)
# 999 → 500, everything else kept

In [46]:
#safe division with np.where
''' np.errstate(...)	with block that temporarily silences numpy warnings (here, divide-by-zero)
np.zeros_like(arr)	New array of zeros with the same shape and dtype as arr (also np.ones_like, np.full_like)
np.divide(a, b, out=, where=)	Division that only computes where where is True and leaves out untouched elsewhere'''
num = np.array([10., 0., 5.]); den = np.array([2., 0., 0.])

with np.errstate(divide="ignore", invalid="ignore"):
    ratio = np.where(den > 0, num / den, 0.0)        # [5. 0. 0.]

np.divide(num, den, out=np.zeros_like(num), where=den > 0)   # [5. 0. 0.]

array([5., 0., 0.])

In [47]:
#np.select(condlist, choicelist, default) is SQL's CASE WHEN … WHEN … ELSE … END
night = (hour >= 22) | (hour < 6)
conds = [
    (amount > 500),
    (amount > 100) & night,
    (amount > 100),
]
choices = ["block", "review", "monitor"]
action = np.select(conds, choices, default="allow")
print(action)

['allow' 'review' 'allow' 'allow' 'block' 'allow' 'allow' 'review' 'allow'
 'allow']


In [48]:
''' np.clip(arr, lo, hi)	Caps values at both ends in one call. Cleaner than two np.wheres for winsorising
np.digitize(arr, bins)	Returns which bin each value falls into (0 = below the first edge). The numpy version of pd.cut
names[...]	Fancy indexing from 4b: turns bin numbers into labels '''
np.clip(amount, 10, 500)
# [ 12.5 230. 45. 10. 500. 60. 15. 410. 33. 75. ]   8.99 → 10, 999 → 500

bins = [50, 100, 500]
np.digitize(amount, bins)                 # [0 2 0 0 3 1 0 2 0 1]   bin number per value
names = np.array(["<50", "50-100", "100-500", "500+"])
names[np.digitize(amount, bins)]          # ['<50' '100-500' '<50' '<50' '500+' ...]

array(['<50', '100-500', '<50', '<50', '500+', '50-100', '<50', '100-500',
       '<50', '50-100'], dtype='<U7')

In [ ]:
#4d: Outlier detection in pure numpy

#method 1 zscore
def zscore_outliers(x, threshold=3.0):
    x = np.asarray(x, dtype=float)
    mu = np.nanmean(x)
    sd = np.nanstd(x, ddof=1)
    if sd == 0 or np.isnan(sd):
        return np.zeros(x.shape, dtype=bool)
    z = (x - mu) / sd
    return np.abs(z) > threshold

#IQR methd
def iqr_outliers(x, k=1.5):
    x = np.asarray(x, dtype=float)
    q1, q3 = np.nanpercentile(x, [25, 75])
    iqr = q3 - q1
    lower, upper = q1 - k * iqr, q3 + k * iqr
    return (x < lower) | (x > upper)
