In [3]:
#1D array
import numpy as np
arr= np.array([1,2,3,4])

print(arr)
print(type(arr))
print(arr.ndim) #gives dimension
print(arr[2])
print(arr[1] - arr[0])

[1 2 3 4]
<class 'numpy.ndarray'>
1
3
1


In [11]:
#2-D
import numpy as np

arr=np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print(arr.ndim) #gives dimension
print(arr[1,2])
print(arr[1,1] - arr[0,0])
print('Last element from 2nd dim: ', arr[1, -1])

[[1 2 3 4]
 [5 6 7 8]]
2
7
5
Last element from 2nd dim:  8


In [10]:
#3d

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,0])
print(arr.ndim) #gives dimension
print(arr[1,1])


10
3
[10 11 12]


In [13]:
#slicing 1d array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #start:end
print(arr[1:5:2]) #start:end:setps

[2 3 4 5]
[2 4]


In [24]:
#slicing 2-d array
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])
print(arr.dtype)  
print(arr.shape) 

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
int64
(2, 5)


In [18]:
#datatype
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [21]:
#defining datatype of arr
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [23]:
#copy & view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y=arr.view()
arr[0] = 42

print(arr)
print(x)
print(y)


[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


In [30]:
#reshaping array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
newarr = arr.reshape(2, 3, 2)
print(newarr)
print(newarr.ndim)
print(newarr.shape)


int64
(12,)
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [33]:
#vectorisation:Vectorisation means doing an operation on the whole array at once, without writing a Python for loop.
import numpy as np

nums = np.array([1, 2, 3, 4])
doubled = nums * 2
print(doubled)


[2 4 6 8]


In [37]:
#universal functions

import numpy as np
x = np.array([1, 4, 9, 16])

print(np.sqrt(x))    # [1., 2., 3., 4.]
print(np.log(x))      # natural log of each item
print(np.exp(x))      # e to the power of each item
np.abs(np.array([-3, 5, -1]))   # [3, 5, 1]

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


array([3, 5, 1])

In [38]:
#np.where(condition, value_if_true, value_if_false) is the vectorised version of an if/else.
import numpy as np

marks = np.array([45, 78, 62, 90, 30])

passed = marks >= 50
# [False, True, True, True, False]   ← a "mask"

marks[passed]
# [78, 62, 90]   ← only the passing marks

np.where(marks >= 50, "Pass", "Fail")
# ['Fail', 'Pass', 'Pass', 'Pass', 'Fail']

array(['Fail', 'Pass', 'Pass', 'Pass', 'Fail'], dtype='<U4')

In [39]:
#broadcasting
import numpy as np
M = np.array([[1, 2, 3],
              [4, 5, 6]])     # shape (2, 3)

row = np.array([10, 20, 30])  # shape (3,)

M + row
# [[11, 22, 33],
#  [14, 25, 36]]

array([[11, 22, 33],
       [14, 25, 36]])

In [42]:
#aggregation
import numpy as np
x = np.array([4, 8, 15, 16, 23, 42])

print(x.sum())# 108
print(x.mean())     # 18.0
print(x.min())      # 4
print(x.max() )     # 42
print(x.std())      # standard deviation (how spread out)
print(x.argmax())   # 5  ← the POSITION of the max, not the value
print(x.argmin())   # 0

108
18.0
4
42
12.315302134607444
5
0


In [47]:
#Linear algebra
# * and @notation
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A * B)       # element-wise: each item times the matching item
# [[ 5, 12],
#  [21, 32]]

A @ B       # MATRIX multiplication (same as np.dot(A, B))
# [[19, 22],
#  [43, 50]]



[[ 5 12]
 [21 32]]


array([[19, 22],
       [43, 50]])

In [48]:
#dot product
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

u @ v          # 1×4 + 2×5 + 3×6 = 32
np.dot(u, v)   # 32 (same thing)


np.int64(32)

In [49]:
#transpose

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

A.T

array([[1, 3],
       [2, 4]])

In [53]:
#identity matrix

import numpy as np

I=np.eye(3)
print(I)

np.linalg.det(I) # determinenet

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

In [56]:
#inverse,solve

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
# [[-2. ,  1. ],
#  [ 1.5, -0.5]]

A @ A_inv
# [[1., 0.],
#  [0., 1.]]     (tiny rounding errors like 1e-16 are normal)



array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [57]:
#solve
import numpy as np
A = np.array([[2, 1],
              [1, 3]])
b = np.array([5, 10])

np.linalg.solve(A, b)
# [1., 3.]   → x = 1, y = 3

array([1., 3.])

In [58]:
#eignevalues
import numpy as np

vals, vecs = np.linalg.eig(np.array([[2, 0],
                                     [0, 3]]))
vals    # [2., 3.]


array([2., 3.])